fix: mypy complaining about ruamel
On macOS, mypy fails with:

```
src/instructlab/config/show.py:7: error: Skipping analyzing "ruamel":
module is installed, but missing library stubs or py.typed marker
[import-untyped]
```

We don't need to install the stubs. So just importing what we need makes
mypy pass. Most likely because our imports are well-typed.

Signed-off-by: Sébastien Han <seb@redhat.com>